version: "3.7"

services:
    backend:
        container_name: backend-dev
        build:
            target: develop-stage
        ports:
            - 8000:8000
        volumes: 
            - ./backend:/var/www

    frontend:
        container_name: frontend-dev
        build:
            target: develop-stage
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app