version: "3.7"

services:
    backend:
        container_name: backend-dev
        build:
            target: develop-stage
        ports:
            - 8000:8000
        volumes: 
            - ./backend:/var/www

    frontend:
        container_name: frontend-dev
        build:
            target: develop-stage
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app

    db:
        container_name: db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'wasakbasak'
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-passsword1!}
        ports:
            - ${DB_PORT:-33060}:3306
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/conf:/etc/mysql/conf.d
